"""empty message

Revision ID: 02875a43b2d7
Revises: ec1fe459cac6
Create Date: 2025-04-16 22:19:16.654454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02875a43b2d7'
down_revision = 'ec1fe459cac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
